import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/header"
import Form from "../components/form"
import Footer from "../components/footer"
export default function Home() {
  return (
    <div className={"bg-background"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Form />
        <div className={"w-full flex items-center justify center flex-col mt-[40px] lg:mt-[60px]"}>
          <span className={'block text-accent-1 rotate-180 text-[25px] leading-none lg:text-[39px]'}>v</span>
          <span className={'block text-accent-1 rotate-180 text-[25px] leading-none  lg:text-[39px]'}>v</span>
        </div>
        <Footer />
      </main>
    </div>
  )
}
